version: '3'
services:
  eureka:
    container_name: eureka
    image: giulianoespejo/microservice-eureka:latest
    ports:
      - "8761:8761"
    environment:
      - SERVER_PORT=8761
    networks:
      - mynetwork

  gateway:
    container_name: gateway
    image: giulianoespejo/microservice-gateway:latest
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
    depends_on:
      - eureka
    networks:
      - mynetwork

  student:
    container_name: student
    image: giulianoespejo/microservice-student:latest
    ports:
      - "8090:8090"
    environment:
      - SERVER_PORT=8090
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:student_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create
    depends_on:
      - eureka
    networks:
      - mynetwork

  course:
    container_name: course
    image: giulianoespejo/microservice-course:latest
    ports:
      - "9090:9090"
    environment:
      - SERVER_PORT=9090
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:course_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create
    depends_on:
      - eureka
    networks:
      - mynetwork

  config-server:
    container_name: config-server
    image: giulianoespejo/microservice-config:latest
    ports:
      - "8888:8888"
    environment:
      - SERVER_PORT=8888
      - SPRING_PROFILES_ACTIVE=native
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
