server:
  port: 8761 # Puerto del proyecto

spring:
  application:
    name: msvc-eureka # Nombre de la aplicación

eureka:
  instance:
    hostname: eureka # Nombre del contenedor para el servicio Eureka
  client:
    register-with-eureka: false # Evita que Eureka se registre a sí mismo
    fetch-registry: false # Evita que Eureka obtenga el registro de sí mismo
    service-url:
      defaultZone: http://eureka:8761/eureka/ # URL donde Eureka está corriendo
