server:
  port: 9090

spring:
  application:
    name: msvc-course
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:course_db
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true  # Habilitar la consola de H2
      path: /h2-console  # Ruta para acceder a la consola

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka